name: LibTorch Linux CUDA x86_64

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The name of the branch you want to build.
        required: true

jobs:
  build:
    runs-on: ['ubuntu-latest']
    strategy:
      matrix:
        cuda: ['128', '129']
        config: ['Debug', 'Release']
        include:
          - cuda: '128'
            container: nvidia/cuda:12.8.1-cudnn-devel-ubuntu22.04
          - cuda: '129'
            container: nvidia/cuda:12.9.0-cudnn-devel-ubuntu22.04

    container: ${{ matrix.container }}
    defaults:
      run:
        shell: bash -el {0}
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v3
      - name: Install compilation tools
        run: |
          apt-get update
          apt-get install -y build-essential curl
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pytorch
      - name: Conda deps
        run: |
          conda install cmake ninja python git zip
      - name: Install MAGMA
        run: |
          curl -OLs https://ossci-linux.s3.us-east-1.amazonaws.com/magma-cuda${{ matrix.cuda }}-2.6.1-1.tar.bz2
          tar -xjf magma-cuda${{ matrix.cuda }}-2.6.1-1.tar.bz2
          mkdir -p /usr/local/magma
          mv include /usr/local/magma/include
          mv lib /usr/local/magma/lib
      - name: Clone
        run: |
          git clone -b ${{ github.event.inputs.branch }} --recurse-submodule https://github.com/pytorch/pytorch.git
      - name: Install deps
        run: | 
          cd pytorch
          pip install -r requirements.txt
          pip install mkl-static mkl-include
      - name: Build Libtorch
        env:
          TORCH_CUDA_ARCH_LIST: "6.1+PTX"
          MAGMA_HOME: /usr/local/magma
        run: |
          ln -s "$CONDA_PREFIX/lib" "$CONDA_PREFIX/lib/intel64"
          mkdir pytorch-build
          cd pytorch-build
          cmake \
            -DBUILD_SHARED_LIBS:BOOL=ON \
            -DCMAKE_BUILD_TYPE:STRING=Release \
            -DBUILD_PYTHON=OFF \
            -DUSE_CUDA=ON \
            -DUSE_NCCL=OFF \
            -DBLAS=MKL \
            -DINTEL_MKL_DIR=$CONDA_PREFIX \
            -DMKL_THREADING=SEQ \
            -DCMAKE_INSTALL_PREFIX:PATH=../libtorch \
            ../pytorch
          cmake --build . --target install --parallel 8 --config ${{ matrix.config }}
      - name: Create archive
        run: |
          zip -r libtorch-linux-cuda${{ matrix.cuda }}-${{ matrix.config }}-x86_64-${{ github.event.inputs.branch }}.zip libtorch/
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: libtorch-linux-cuda${{ matrix.cuda }}-${{ matrix.config }}-x86_64-${{ github.event.inputs.branch }}.zip
          overwrite: true
          file_glob: true
          tag: LibTorch-for-R

